services:
  piston:
    image: ghcr.io/engineer-man/piston
    container_name: piston_api
    restart: unless-stopped
    privileged: true
    ports:
      - "2000:2000"
    volumes:
      - piston-data:/piston
    environment:
      - PISTON_RUN_TIMEOUT=30000
      - PISTON_RUN_CPU_TIME=20000

  backend:
    build: ./backend
    container_name: pseudogo_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - piston
    environment:
      - PISTON_URL=http://piston:2000/api/v2/execute
      - ALLOWED_ORIGIN=http://localhost:4200

volumes:
  piston-data: